# Aliases
alias py="python"
alias d="docker"
alias dc="docker-compose"
alias dn="dotnet"
alias gs="git status"
alias gadd="git add ."
alias gc="git commit"
alias gp="git push"
alias gpull="git pull"
alias k="kubectl"
alias ld="lazydocker"
alias lg="lazygit"
alias le="set -a ; source .env ; set +a"
alias hq="harlequin"
alias h="herdr"
