# Aliases
alias py="python"
alias d="docker"
alias dc="docker-compose"
alias dn="dotnet"
alias gs="git status"
alias gadd="git add ."
alias gc="git commit"
alias gp="git push"
alias gpull="git pull"
alias update="sudo apt update -y && sudo apt dist-upgrade -y && sudo apt autoclean ; sudo apt autoremove -y"
alias ld="lazydocker"
alias lg="lazygit"
alias le="set -a ; source .env ; set +a"
alias backup="rsync -rv --exclude=venv projects projects-old"
